name: Synk POC
on:
  workflow_dispatch:
  push: # on push to master branch
    branches:
      - synk_poc
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
